### ISSUE TITLE
Windows smaller than 400px are not handled properly

### ISSUE THREAD

**Issue by ShawnHeyli** [ShawnHeyli/friendlyfire#11]
In player.ts [this code](https://github.com/ShawnHeyli/friendlyfire/blob/49cc37c656950daf73a526e07bf9d84be9c6de20/client/src/player.ts#L28-L35) does not handle small images, we could either scale up those images or keep them as they are. I think scaling them is more appropriate

**Comment by ErrorTeaPot** [comment]
@ShawnHeyli Tu peux fermer l'issue ?

**Comment by ShawnHeyli** [comment]
Fixed by #12
