### ISSUE TITLE
Ajouter un fork()/deamon()

### ISSUE THREAD

**Issue by ErrorTeaPot** [ShawnHeyli/friendlyfire#15]
Ajouter un fork() ou un deamon() pour faire en sorte que le binaire reste lancé quand on ferme le terminal

**Comment by ShawnHeyli** [comment]
Mais quand on dev on veut le terminal pour les logs et en release on a pas de terminal vu qu'on execute juste un binaire

**Comment by ErrorTeaPot** [comment]
Dans le cas de l'exec du binaire ça fork bien ?

**Comment by ErrorTeaPot** [comment]
On peut faire en sorte que par défaut ça fork() et ajouter une option --debug pour le garder dans le terminal si besoin. Ou alors ajouter du logging.

**Comment by ShawnHeyli** [comment]
Après essaie de lancer des GUI (anki, firefox, dolphin, bitwarden) tu verra que ça reste toujours dans le terminalm j'ai l'impression que le paradigme le plus commun c'est de laisser le fardeau sur l'utilisateur

**Comment by ErrorTeaPot** [comment]
Plus nécessaire depuis la création d'un [fichier .desktop](https://github.com/ShawnHeyli/friendlyfire/commit/e3bb141127796d6c00001b52cabec8c74664f601)
