### ISSUE TITLE
Utiliser des event handlers

### ISSUE THREAD

**Issue by ErrorTeaPot** [ShawnHeyli/friendlyfire#7]
Utiliser des event handler pour récupérer les infos du serveur plutôt que GET comme un singe

**Comment by ShawnHeyli** [comment]
Pour l'instant le /healthcheck fait suffisament le boulot, un event handler amène avec lui des problèmes de synchronisation et ne permet pas d'être sur de l'état du serveur à un instant T. 
Mais une solution comme celle proposée pourrait être implémentée en option plus tard
